### ISSUE TITLE
Create "SamplingFeatureDatasets" endpoint

### ISSUE THREAD

**Issue by aufdenkampe** [ODM2/ODM2RESTfulWebServices#19]
See https://docs.google.com/document/d/1hwUr514gm5JlqUuGkowyF-llbWpTaPo62ZyONDF5Zzg/edit#bookmark=id.gdfwky2r5gvf

Requires new function in https://github.com/ODM2/ODM2PythonAPI

**Comment by Elijahwalkerwest** [comment]
Implemented and merged. Closing

**Comment by horsburgh** [comment]
@Elijahwalkerwest - can you please try and catch @sreeder before she leaves today. She and I discussed a reorganization of the object structure for the ODM2 Python API getSamplingFeatureDatasets() function. If she's done this, then this REST endpoint needs to be updated to match where she ended up.

**Comment by Elijahwalkerwest** [comment]
She mentioned that to me, we've been communicating. I had assumed that would be a separate issue in git, but yes that re-structure we have communicated about.

**Comment by horsburgh** [comment]
Let's just use this issue until we have an initial implementation that matches what it should be.

**Comment by emiliom** [comment]
Endpoint is implemented. Closing.
