### ISSUE TITLE
Update URL in repo description

### ISSUE THREAD

**Issue by aufdenkampe** [ODM2/ODM2RESTfulWebServices#28]
This no longer works.
http://52.32.161.233:8001/v1/docs/

**Comment by lsetiawan** [comment]
Works now 😄 was working on it.

**Comment by aufdenkampe** [comment]
Wow, you're fast!

**Comment by emiliom** [comment]
@lsetiawan are you working on it again? It's not working for me.

I don't really need it; it's just reassuring and helpful to have it be working.

**Comment by lsetiawan** [comment]
I'm not touching it. Thanks. Not sure what's going on.. :/
