### ISSUE TITLE
New function in the API

### ISSUE THREAD

**Issue by sreeder** [ODM2/ODM2RESTfulWebServices#36]
Functions in the ODM2PythonAPI
New:
getDatasetvalues
getDatasetresults

update parameters:
getDatasets

**Comment by horsburgh** [comment]
@sreeder - I'm going to close this issue because it isn't actionable. These new functions are in the ODM2 Python API. The Datasets REST endpoint needs to be updated to use the latest getDatasets function. The other two will be referenced by new create endpoint issues I will post.
