### ISSUE TITLE
Create "actions" endpoint

### ISSUE THREAD

**Issue by horsburgh** [ODM2/ODM2RESTfulWebServices#37]
Create actions endpoint. See the REST API design document:

https://docs.google.com/document/d/1hwUr514gm5JlqUuGkowyF-llbWpTaPo62ZyONDF5Zzg/edit#bookmark=id.ywovhcwljxvg

This should use the ODM2 Python API getActions() function.

**Comment by lsetiawan** [comment]
Resolved by #45
