### ISSUE TITLE
Create "datasetresults" endpoint

### ISSUE THREAD

**Issue by horsburgh** [ODM2/ODM2RESTfulWebServices#38]
Create datasetresults endpoint. See the REST API design document:

https://docs.google.com/document/d/1hwUr514gm5JlqUuGkowyF-llbWpTaPo62ZyONDF5Zzg/edit#bookmark=id.uiqgg8ue0nvg

This should use the getDatasetResults() function in the ODM2 Python API

**Comment by Elijahwalkerwest** [comment]
I see this function in the REST API, but no updates here. Confirming with whoever implemented, is this OK to close?

**Comment by lsetiawan** [comment]
If its on the demo site, it's ready to close. Thanks.

**Comment by lsetiawan** [comment]
DONE.
