### ISSUE TITLE
Create "datasetvalues" endpoint

### ISSUE THREAD

**Issue by horsburgh** [ODM2/ODM2RESTfulWebServices#39]
Create datasetvalues endpoint. See the REST API design document:

https://docs.google.com/document/d/1hwUr514gm5JlqUuGkowyF-llbWpTaPo62ZyONDF5Zzg/edit#bookmark=kix.ubirwgjh1n7k 

This endpoint should use the getDatasetValues() function of the ODM2 Python API.

**Comment by lsetiawan** [comment]
Implemented by @Elijahwalkerwest.
