### ISSUE TITLE
Create "organizations" endpoint

### ISSUE THREAD

**Issue by horsburgh** [ODM2/ODM2RESTfulWebServices#40]
Create organizations endpoint. See the REST API design document:

https://docs.google.com/document/d/1hwUr514gm5JlqUuGkowyF-llbWpTaPo62ZyONDF5Zzg/edit#bookmark=id.bvxx6xmc6qh8

This should use the ODM2 Python API getOrganizations() function.

**Comment by lsetiawan** [comment]
DONE.
