### ISSUE TITLE
Create "processinglevels" endpoint

### ISSUE THREAD

**Issue by horsburgh** [ODM2/ODM2RESTfulWebServices#41]
Create processinglevels endpoint. See REST API design document:

https://docs.google.com/document/d/1hwUr514gm5JlqUuGkowyF-llbWpTaPo62ZyONDF5Zzg/edit#bookmark=id.gmhj0ynlv4q

This endpoint should use the ODM2 Python API getProcessingLevels() function.

**Comment by lsetiawan** [comment]
Implemented in PR #56
