### ISSUE TITLE
Create "samplingfeaturedatasets" endpoint

### ISSUE THREAD

**Issue by horsburgh** [ODM2/ODM2RESTfulWebServices#42]
Create samplingfeaturedatasets endpoint. See REST API design document:

https://docs.google.com/document/d/1hwUr514gm5JlqUuGkowyF-llbWpTaPo62ZyONDF5Zzg/edit#bookmark=id.gdfwky2r5gvf

This endpoint should use the ODM2 Python API function getSamplingFeatureDatasets().

**Comment by lsetiawan** [comment]
This was addressed by #27.
