### ISSUE TITLE
Create "units" endpoint

### ISSUE THREAD

**Issue by horsburgh** [ODM2/ODM2RESTfulWebServices#43]
Create units endpoint. See the ODM2 REST API design document:

https://docs.google.com/document/d/1hwUr514gm5JlqUuGkowyF-llbWpTaPo62ZyONDF5Zzg/edit#bookmark=id.dogtoo8iqko0

This endpoint should use the ODM2 Python API getUnits() function.

**Comment by lsetiawan** [comment]
Has been added. Closing.
