### ISSUE TITLE
Create "variables" endpoint

### ISSUE THREAD

**Issue by horsburgh** [ODM2/ODM2RESTfulWebServices#44]
Create variables endpoint. See the REST API design document:

https://docs.google.com/document/d/1hwUr514gm5JlqUuGkowyF-llbWpTaPo62ZyONDF5Zzg/edit#bookmark=id.qx9svbvhkehr

This endpoint should use the ODM2 Python API getVariables() function.

**Comment by lsetiawan** [comment]
Has been added. Closing.
