### ISSUE TITLE
Migrate to spyne (from soaplib?)

### ISSUE THREAD

**Issue by emiliom** [ODM2/ODM2RESTfulWebServices#5]
@valentinedwv  suggested moving to Spyne, so it can be used in Multiple Frameworks. [Spyne](http://spyne.io) is used by WOFpy (UCSD team [introduced it in 2015 / early 2016](https://github.com/ODM2/WOFpy/issues/13)). Spyne is a revision of the `soaplib` SOAP toolkit, and allows RESTful web services

**Comment by emiliom** [comment]
Adding comment from @valentinedwv from an older issue (that I missed originally), so it can be closed for housekeeping. It had not follow-up discussion.

> Refactor to use spyne so we get multiple server stacks, multiple protocols.

**Comment by aufdenkampe** [comment]
Closing, given the recent reorg/refactor of the repo, and the decision to move away from Spyne (and base on Django + SQLAlchemy).
