### ISSUE TITLE
List json output for one object or just the one object

### ISSUE THREAD

**Issue by lsetiawan** [ODM2/ODM2RESTfulWebServices#52]
The title might be confusing, but I'm trying to figure out whether the output of a single result should just be a single json object or in a list. Currently it's the single. Thanks.

Single:
``` json
 {
    "PersonID": 24,
    "PersonFirstName": "Some",
    "PersonMiddleName": "S.",
    "PersonLastName": "Person"
  }
```

List:
```json
[
  {
    "PersonID": 24,
    "PersonFirstName": "Some",
    "PersonMiddleName": "S.",
    "PersonLastName": "Person"
  }
]
```

**Comment by lsetiawan** [comment]
ping @emiliom

**Comment by horsburgh** [comment]
I vote for consistency. If the endpoint is capable of returning a list, then it should always return a list.

**Comment by lsetiawan** [comment]
I am implementing a consistent return of list. Thanks.
