### ISSUE TITLE
Result values keys lower case or match Python API model?

### ISSUE THREAD

**Issue by lsetiawan** [ODM2/ODM2RESTfulWebServices#55]
Currently, result values keys are all lower case since this is how it's displayed within the pandas dataframe.

Example: 

```json
[
  {
    "valueid": 1064,
    "resultid": 1064,
    "datavalue": 1.2256,
    "valuedatetime": "2015-11-17T13:55:12",
    "valuedatetimeutcoffset": -7
  }
]
```

Do we want this to be this way or the keys should be `CamelCase` like any other model? If so, I either have to figure out the camel case conversion/mapping or this should be implemented within ODM2PythonAPI.

**Comment by emiliom** [comment]
The only `odm2api` query that returns a pandas Dataframe is the one for ResultValues. I forget, but what do other queries returns as far as case for properties -- CamelCase, right? If they're all CamelCase:
- I agree, this should be implemented in `odm2api` (though it may break current usage)
- In the short term (work you're doing right now), I'd keep things simple -- and less hard-wired work -- and consistent with odm2api, and use lowercase. A conversion to CamelCase can be done in sync with an odm2api implementation

My 3 cents. Thanks.

**Comment by emiliom** [comment]
If all other queries do in fact return CamelCase, please open an `odm2api` github issue to point out this inconsistency and express a future need to change the resultvalues query.

**Comment by lsetiawan** [comment]
Thanks @emiliom. That answers my question. It seems like currently [getResultValues](https://github.com/ODM2/ODM2PythonAPI/blob/development/odm2api/ODM2/services/readService.py#L1274) is the only functions that outputs to Pandas DataFrame, and have this all lowercase names. I'll open up an Issue in `odm2api`.

**Comment by emiliom** [comment]
PR #77 (and related discussions) addressed this issue. All results are now returned as CamelCase. Closing.
