### ISSUE TITLE
Issue a release

### ISSUE THREAD

**Issue by emiliom** [ODM2/ODM2RESTfulWebServices#59]
@lsetiawan after an initial batch of testing of the new endpoints (hopefully with help from others ...), I think it'd be a good idea to issue a tagged release.

**Comment by lsetiawan** [comment]
Noting here that a release of `odm2rest` will require a new release of `odm2api` first because a lot of the more complex endpoints require the latest changes, which are not in master.

**Comment by emiliom** [comment]
Thanks for following up this topic via this existing issue! As I mentioned, I'll follow up on the odm2api repo.

**Comment by emiliom** [comment]
Alrighty. With PR #77 merged, I think everything is ready to issue a first tagged release, and then a first conda package, right @lsetiawan? If so, please work on that this week, starting possibly tomorrow.

**Comment by lsetiawan** [comment]
@Maurier @Elijahwalkerwest @horsburgh 

I would like to inform you that there will be a first release of `odm2rest` very soon. 

**Please Note**:

1) See PR https://github.com/ODM2/ODM2RESTfulWebServices/pull/73 for a major change from probably the previous copy that you have. `odm2rest` is now a reusable django app that should be pluggable to existing django application. 

2) See PR https://github.com/ODM2/ODM2RESTfulWebServices/pull/77 for the detail about *values endpoint having keys casing that are exactly the same as the odm2 database table columns. They are not lowercase anymore.

Other than those two things. I think that everything works the same. Please let me know if you have any questions. Thanks.

**Comment by lsetiawan** [comment]
@emiliom After that last PR #78, which has been approved by Filipe. We are ready to issue a first tagged release. Are you going to prepare this or you'd like me to? Thanks.

**Comment by emiliom** [comment]
@lsetiawan Please prepare the release yourself in **draft** mode, and I'll review (after you ping me) it before we make it real/official.

**Comment by lsetiawan** [comment]
This should be v0.1 pre-release correct?

**Comment by emiliom** [comment]
> This should be v0.1 pre-release correct?

Yup. And also labelled "alpha" (see odm2api and wofpy to get a better sense of the version tagging conventions we've used in ODM2).

**Comment by lsetiawan** [comment]
@emiliom I've created a release draft. Please not sure how detailed it should be, since it's a first release. Thanks.

**Comment by emiliom** [comment]
I've reviewed, edited (minor) and issue the release: https://github.com/ODM2/ODM2RESTfulWebServices/releases/tag/v0.1.0-alpha

@lsetiawan please follow up with @ocefpaf in requesting the creation of a conda package via a new issue at https://github.com/ODM2/conda-recipes-ODM2

**Comment by emiliom** [comment]
@Maurier @horsburgh @aufdenkampe @miguelcleon 

The first [tagged release](https://github.com/ODM2/ODM2RESTfulWebServices/releases/tag/v0.1.0-alpha) of the ODM2 REST API ("odm2rest") was issued two days ago, and the first [conda package](also "odm2rest") was minted and tested minutes ago. Woo-hoo!

Great job, @lsetiawan and @ocefpaf ! Thanks.

**Comment by emiliom** [comment]
Whoops, wrong url for the conda package: https://anaconda.org/odm2/odm2rest

(not that it matters ... no one ever needs to go there except for admin purposes)

**Comment by aufdenkampe** [comment]
Thanks for this great work!
Is there a deployment for us to explore?

Sent from my iPhone

On Feb 2, 2018, at 1:22 PM, Emilio Mayorga <notifications@github.com<mailto:notifications@github.com>> wrote:


Whoops, wrong url for the conda package: https://anaconda.org/odm2/odm2rest

(not that it matters ... no one ever needs to go there except for admin purposes)

-

**Comment by Elijahwalkerwest** [comment]
I will have a deployment of the latest release ready for you to explore a little later on today.  Ill update you here as soon as it's ready.

**Comment by lsetiawan** [comment]
Thanks for taking care of this @Elijahwalkerwest  👍 

I'll probably update my sample deployment tomorrow maybe.

**Comment by Elijahwalkerwest** [comment]
@aufdenkampe  There is a working deployment at http://odm2wofpy1.uwrl.usu.edu/v1/docs/

Browse through that swagger interface and give it a test!

**Comment by Elijahwalkerwest** [comment]
@lsetiawan  the http://odm2wofpy1.uwrl.usu.edu/v1/docs/ is the most recent release.
