### ISSUE TITLE
Recover and deploy previous working demos on UW AWS

### ISSUE THREAD

**Issue by emiliom** [ODM2/ODM2RESTfulWebServices#6]
Following up on discussion with @valentinedwv at BiGCZ call on May 30. Creating this issue to track discussions and progress.

David, have you had a chance to look at the old VMs to see if you can recover and deploy them on an Amazon AWS cloud instance hosted by the UW (that we'll give you access to)? FYI, we're now ready to go as of today with a dedicated BiGCZ AWS instance we can use for this. @lsetiawan (Don) will manage it.

As we discussed, the goal here is to redeploy exactly what was previously live on the Azure instance that SDSC managed. No enhancements or changes to anything whatsoever is needed.

cc @aufdenkampe

**Comment by cdesyoun** [comment]
Based on David's request, I will try to rebuild old ODM2 rest API service.
How can I access your AWS cloud instance?

**Comment by horsburgh** [comment]
@cdesyoun and @emiliom - I'm going to message the USGS guys and let them know we are working to stand this up again. Can you please let me know when it is working again so I can send them the pertinent information?

**Comment by emiliom** [comment]
Thanks, Choonhan. @lsetiawan, please follow up with @cdesyoun to give him the access and set up he needs on our AWS cloud. Probably best to do that offline, via email. I'll connect you two.

**Comment by cdesyoun** [comment]
@emiliom , @horsburgh @valentinedwv, I deployed old ODM2 rest swagger api on AWS cloud.
Here is the link, http://54.213.227.245:8080/docs/

Thanks,
Choonhan Youn

**Comment by emiliom** [comment]
Thank you, Choonhan! Fantastic.

FYI (for others), the service provides access to my "Marchantaria" ODM2 use case. This [Jupyter notebook](https://github.com/BiG-CZ/BiG-CZ-Toolbox/blob/master/ipynotebooks/ODM2RESTdemo_MarchantariaUseCase.ipynb) from August 2015 provides sample access information and background on the use case (assumptions, data loaded, etc); additional information on this use case is available on our ODM2 use case paper:

Hsu, L. et al., (2017). Enhancing Interoperability and Capabilities of Earth Science Data using the Observations Data Model 2 (ODM2). Data Science Journal. 16, p.4. DOI: http://doi.org/10.5334/dsj-2017-004

Issue #1 from 2015-2016 also includes some discussion on the REST API implementation vis a vis this use case.

**Comment by aufdenkampe** [comment]
@emiliom, time to close this issue?

**Comment by emiliom** [comment]
Sure. Closing.
