### ISSUE TITLE
Documentation on "production" deployment

### ISSUE THREAD

**Issue by lsetiawan** [ODM2/ODM2RESTfulWebServices#66]
@Elijahwalkerwest have said that he successfully deploy odm2restapi in a production mode.

His setup are (I think):
- NGINX
- Gunicorn
- Django

He is currently compiling the documentation for this.

**Comment by Elijahwalkerwest** [comment]
NginX
Gunicorn
Django

Will have documentation ready this week for my deployment.

**Comment by lsetiawan** [comment]
Documentation can be found [here](https://github.com/ODM2/ODM2RESTfulWebServices/blob/master/docs/production_deployment.md)
