### ISSUE TITLE
Need packages in conda 

### ISSUE THREAD

**Issue by lsetiawan** [ODM2/ODM2RESTfulWebServices#68]
@ocefpaf Do you still have some time to work on bigcz project? If so, could you please package the three libraries below into conda so I can use install through conda rather than pip. Thanks!

- [`djangorestframework-csv`](https://github.com/mjumbewu/django-rest-framework-csv)
- [`djangorestframework-xml`](https://github.com/jpadilla/django-rest-framework-xml)
- [`djangorestframework-yaml`](https://github.com/jpadilla/django-rest-framework-yaml)

**Comment by lsetiawan** [comment]
Pinging @ocefpaf about this issue again. :)

**Comment by emiliom** [comment]
Happy New Year @ocefpaf !

Your help on this will be much appreciated. In addition, @lsetiawan will be asking you later on (next week or so?) for help in creating a conda package out of this (ODM2RESTfulWebServices
) software.

**Comment by ocefpaf** [comment]
Happy new year :tada: 

I'm back from my vacation and I'll look at this ASAP.
