### ISSUE TITLE
Update /resultvalues endpoint

### ISSUE THREAD

**Issue by lsetiawan** [ODM2/ODM2RESTfulWebServices#75]
Once PR https://github.com/ODM2/ODM2PythonAPI/pull/136 is merged `/resultvalues` need to be updated.

**Comment by emiliom** [comment]
Thanks for staying on top of this :smiley: 

I'll repeat (and tweak) the comment I made on https://github.com/ODM2/ODM2PythonAPI/pull/136:

Let's make sure Jeff et al are very aware of this change. Correct me if I'm wrong, but all existing code that uses output from this API endpoint will need to be upgraded to the case-sensitive names, right?

**Comment by lsetiawan** [comment]
> but all existing code that uses output from this API endpoint will need to be upgraded to the case-sensitive names, right?

Yes indeed :smile:

**Comment by lsetiawan** [comment]
This Issue was addressed in #76

**Comment by lsetiawan** [comment]
I'm reopening this issue. @emiliom My question now is, should the endpoint also default to lowercase or not?

**Comment by emiliom** [comment]
> My question now is, should the endpoint also default to lowercase or not?

Unlike odm2api, the REST API is very new and experimental, and has very few "live" uses yet. For that reason, we should be more confident in marching ahead with disruptive changes if they result in doing what's best in the long run.

So, I suggest you should stick with having the REST API return CamelCase responses. But please work with whoever is actively using the REST API code to give them (him?) a heads up. If I remember correctly, it's mainly one person in Jeff's team who is working on the "Sample Data Viewer", right?

**Comment by horsburgh** [comment]
@Elijahwalkerwest would need to do a new deployment for us, and @Maurier would need to update his specimen data viewer code to make sure it works if you change the casing.

**Comment by emiliom** [comment]
Thanks, @horsburgh! @lsetiawan please work with them in laying out a workable transition timeframe.

BTW, I see no tagged released has ever been issued for ODM2 REST API. See #59. Maybe we (meaning @lsetiawan :smiley_cat: ) should first work towards a first release that freezes the current state of the ODM2 REST API? Then it'll be cleaner to roll out these enhancements as a new release.

**Comment by lsetiawan** [comment]
This endpoint has been resolved, Preparing for release... Closing.
