### ISSUE TITLE
ODM2REST Test on ODM2LCZO Database (Miguel's Data)

### ISSUE THREAD

**Issue by lsetiawan** [ODM2/ODM2RESTfulWebServices#8]
## Overview

I went ahead and tested ODM2RESTfulWebServices against @miguelcleon `ODM2LCZO` Postgresql database. This is so that I can really wrap my head around the mechanics of what's going on since, I am more familiar with this dataset.

ping @emiliom 

## Notes
- My first struggle was to tweak the `*_views.py` `QUERY_PARAMS` to `query_params` due to the function deprecation since django rest framework version 3.0.
- I tested each endpoints, and they all seemed to work except for `actions` and `methods`.
  - Based on the Error, my thinking is that this is caused by the data itself, rather than the REST API. Though a handling is needed for these kinds of cases (Method not having Organization).

## Endpoint Tests

<details>
<summary>/Observations/</summary>

![observations](https://user-images.githubusercontent.com/17802172/29584370-5fb76c6a-8738-11e7-9ea9-21da517db6f2.png)

</details>

<details>
<summary>/actions/</summary>

![actions](https://user-images.githubusercontent.com/17802172/29584609-2f166dee-8739-11e7-915a-26f2f7596c53.png)

</details>

<details>
<summary>/datasets/</summary>

![datasets](https://user-images.githubusercontent.com/17802172/29585668-d6a59596-873c-11e7-96c1-eea36ca8d731.png)

</details>

<details>
<summary>/externalidentifiers/</summary>

![externalidentifiers](https://user-images.githubusercontent.com/17802172/29584647-477f32f8-8739-11e7-8a8d-75a81261ee32.png)

</details>

<details>
<summary>/methods/</summary>

![methods](https://user-images.githubusercontent.com/17802172/29584689-6835c444-8739-11e7-8923-97fe2a26107f.png)

</details>

<details>
<summary>/organizations/</summary>

![organizations](https://user-images.githubusercontent.com/17802172/29584727-8176b152-8739-11e7-9f85-c7bb0498ba96.png)

</details>

<details>
<summary>/samplingfeatures/</summary>

![samplingfeatures](https://user-images.githubusercontent.com/17802172/29584742-8dcd6b12-8739-11e7-83aa-0a3a58a1d89b.png)

</details>

<details>
<summary>/sites/</summary>

![sites](https://user-images.githubusercontent.com/17802172/29584761-9964689a-8739-11e7-921c-5cdd2c4ca638.png)

</details>

<details>
<summary>/values/</summary>

![values](https://user-images.githubusercontent.com/17802172/29584770-a6ab9596-8739-11e7-85e1-cd188e4e346f.png)

</details>

<details>
<summary>/variables/</summary>

![variables](https://user-images.githubusercontent.com/17802172/29584782-b1607ed4-8739-11e7-8b01-e917088610bd.png)

</details>

**Comment by emiliom** [comment]
Nice! I can see the value of doing this, for helping you wrap your head around the API. But I would caution against investing time in making any changes to the code base at this early phase. For example:

> Though a handling is needed for these kinds of cases (Method not having Organization)

I agree, in general. But I would say you should go ahead with this change **only** if it helps you a lot in using the LCZO database to learn more about how the API works.

**Comment by miguelcleon** [comment]
@lsetiawan yeah, looks like organization is not a required field so someone can leave it blank.

**Comment by lsetiawan** [comment]
> I agree, in general. But I would say you should go ahead with this change only if it helps you a lot in using the LCZO database to learn more about how the API works.

I don't need to make this change right now. Seeing the other requests, I am already starting to understand what's going on. Thanks.

**Comment by lsetiawan** [comment]
This was testing with the old API, not valid anymore with the new code. Will probably open up new Issue in the future when doing testcase.
